COMPONENT=OscilloscopeAppC
CFLAGS+=-DDEFAULT_BAUDRATE=115200		#Basic Sensor
CFLAGS += -DTOSH_DATA_LENGTH=100 # For debugging
PFLAGS+=-DCC2420_DEF_CHANNEL=26
DEFAULT_LOCAL_GROUP=0x26
include $(MAKERULES)
